language: r
cache:
  packages: true
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so not deploying"; fi
warnings_are_errors: false
addons:
  apt:
      packages:
            - gdal-bin
            - libgdal1-dev
            - libproj-dev
            - libudunits2-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libv8-dev
            
install:
  - R -e "install.packages('sf')"
  - R -e "install.packages('tmap')"
    - R -e "install.packages('rmapshaper')"
