language: r

# cache packages so that each build doesn't require installation...
cache:
  packages: true

# Make bash scripts executable, so they can be run later. 
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

script:
- "./_build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so
  not deploying"; fi